### ISSUE TITLE
Form Input validierung

### ISSUE THREAD

**Issue by julia-r** [oxytocinated/2016bt#2]
> - Test Personen, Email -> empty?

Ich habe mal für die Felder Nick, E-Mail und Personen "required" hinzugefügt. Moderne Browser verhindern dann, dass man die Formulare abschicken kann, wenn das nicht ausgefüllt ist. 

> - Test Personen -> Zahl?

Für Personen und die Schnitzel-Felder habe ich type="number" hinzugefügt, damit man dort nur Nummern eingeben kann. Außerdem min="0" bzw. 1, weil negative Werte hier keinen Sinn machen. 

Mehr Infos daszu hier: http://www.html5rocks.com/de/tutorials/forms/html5forms/

Beides funktioniert aber nur in modernen Browsern. Um ganz sicher zu gehen, wäre es besser mit PHP oder Javascript noch mal alles zu validieren.

**Comment by oxytocinated** [comment]
super :)
n00b- Frage: wie denn validieren? (am Liebsten mit php, da ja viele Javascript im Browser ausschalten)

**Comment by julia-r** [comment]
Ich hab mal zwei Beispiele eingebaut. Ich weiß nicht, was die maximale Anzahl von Personen sein, soll, hab jetzt mal 10 genommen.

HINWEIS: Damit du das testen kannst, müsstest du die HTML Validierungs Sachen erstmal zeitweise wieder raus nehmen. (also type = "number" und required usw.)

**Comment by oxytocinated** [comment]
Hm, ich habe die HTML- Sachen rausgenommen, allerdings kommt jetzt eine Aufforderung "Bitte gi eine Zahl zwischen 1 und 10 für die Anzahl der Personen ein!", selbst wenn ich 2 oder 8 oder so eingebe.
Bei "0" kommt nur "Bitte gib an wie viele Personen Du anmelden willst!"

Irgendwas klappt also scheinbar noch nicht

**Comment by julia-r** [comment]
sorry... hab es noch mal geändert. Magst du noch mal testen?

**Comment by oxytocinated** [comment]
Klappt leider noch immer nicht. 
Dann belassen wir's halt doch bei den HTML- Tags.
